### ISSUE TITLE
How to train your model？

### ISSUE THREAD

**Issue by Mushero** [shyam671/Removing-Atmospheric-Turbulence-via-Deep-Adversarial-Learning#1]
Your model is great. I want to train it on my device. How do I train it? What data set format is required?

**Comment by shyam671** [comment]
Hi Mushero,
Thank you for taking an interest in the work.

1. Please download the code from [Link](https://webee.technion.ac.il/~yoav/research/turbulence_distortion.html).
It is a Matlab code that can be utilized to generate atmospheric turbulence. You have to apply these atmospheric turbulence on ImageNet images using the hyperparameters present in TIP paper.
2. Next, you can use these images to train DTD-GAN and DT-GAN using the given code and test it on real atmospheric turbulent images.

-Shyam
